### ISSUE TITLE
loading other tree data

### ISSUE THREAD

**Issue by Liyubov** [lucidmindsai/gus#19]
Hi, 
I tried your library, 
I am working on the tree data in different cities, so I tried to first load and transform my data be able to be processed, but then I got some errors, as I guess that you are also using some raster data for each file you are using?
https://github.com/Liyubov/gus/blob/main/notebooks/GUS_trees_data_loading.ipynb

**Comment by oguzhan** [comment]
Hi @Liyubov 

Can you please point me to the data you used in the notebook? Can't see that line for some reason
The error is related to Matplotlib but I'd like to run it step by step with the same data you used and do some checks

**Comment by Liyubov** [comment]
the data I used are located in this folder arxiv https://github.com/Liyubov/open_tree_data_analysis/tree/main/data
i do not have some values but i transformed some to adjust to what you could need to estimate missing values. 

would be really great to do it automatically somehow for similar tree data...

i also have other data from trees from other cities like this. would this be interesting to work on?

**Comment by oguzhan** [comment]
[datatrees paris.zip](https://github.com/Liyubov/open_tree_data_analysis/blob/main/data/datatrees%20paris.zip)

I downloaded and unzipped this data, but it's empty. Can you please check again?

yes, it'd be great to run it for different cities. We can add them to the repo too

**Comment by oguzhan** [comment]
We have added a new Tutorial that shows how to load city data to gus to run simulations: https://github.com/lucidmindsai/gus/blob/main/notebooks/Amsterdam.ipynb

closing this issue because of no response
