### ISSUE TITLE
Compute light exposure - suggested update

### ISSUE THREAD

**Issue by MarkoLucidminds** [lucidmindsai/gus#2]
https://github.com/lucidmindsai/gus/blob/b3965299a62b7d5092f3160b67f1a67e51d91408/src/gus/agents.py#L335

Could be: 

 overlap = max(0, 0.5 * (self.crown_width + t_w - self.model.dt_resolution))

and 

self.model.dt_resolution = distance among neighbouring trees

**Comment by oguzhan** [comment]
on it!

cc @bulentozel
